Improve bash exports and aliases

diff --git a/bash/utils b/bash/utils
--- a/bash/utils
+++ b/bash/utils
@@ -49,10 +49,19 @@ if [ -f "$PREFIX/opt/fzf/shell/key-bindings.bash" ]; then
 	. "$PREFIX/opt/fzf/shell/key-bindings.bash"
 fi
 
+# See https://github.com/antonmedv/llama
+if hash llama 2>/dev/null; then
+	function la {
+		cd "$(llama "$@")" || echo >&2 'Unable to cd into directory'
+	}
+fi
+
 # Work with multiple versions of Python
 # https://github.com/pyenv/pyenv
 # But don't overcast shims when inside an activated virtualenv sub-shell
 if [ -z "$VIRTUAL_ENV" ] && command -v pyenv 1>/dev/null 2>&1; then
+	# export VIRTUAL_ENV_DISABLE_PROMPT=1
+	export PYENV_VIRTUALENV_DISABLE_PROMPT=1
 	eval "$(pyenv init -)"
 fi
 
